# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jasonwang/Desktop/ece253/lab1b/vivado/vivado.srcs/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
# IP: The module: 'system_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jasonwang/Desktop/ece253/lab1b/vivado/vivado.gen/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jasonwang/Desktop/ece253/lab1b/vivado/vivado.gen/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jasonwang/Desktop/ece253/lab1b/vivado/vivado.gen/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jasonwang/Desktop/ece253/lab1b/vivado/vivado.srcs/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
# IP: The module: 'system_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jasonwang/Desktop/ece253/lab1b/vivado/vivado.gen/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jasonwang/Desktop/ece253/lab1b/vivado/vivado.gen/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jasonwang/Desktop/ece253/lab1b/vivado/vivado.gen/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
